-- Lead Eagle plan, phase 3: a reason on entering a stage (gap 3), QR capture
-- links (gap 4), cold data (gap 5). Generated by migrate diff against a clean
-- database; the RLS block is the one every tenant table carries.

-- CreateEnum
CREATE TYPE "DataStatus" AS ENUM ('NOT_CONTACTED', 'NOT_REACHABLE', 'NOT_INTERESTED', 'INTERESTED', 'CONVERTED', 'INVALID');

-- AlterTable
ALTER TABLE "Lead" ADD COLUMN     "stageReason" TEXT;

-- AlterTable
ALTER TABLE "LeadStage" ADD COLUMN     "reasons" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "requiresReason" BOOLEAN NOT NULL DEFAULT false;

-- CreateTable
CREATE TABLE "CaptureLink" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "headline" TEXT,
    "ownerId" TEXT,
    "campaign" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "openCount" INTEGER NOT NULL DEFAULT 0,
    "submitCount" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdById" TEXT,

    CONSTRAINT "CaptureLink_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DataRecord" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "fullName" TEXT NOT NULL,
    "phone" TEXT,
    "phoneNormalized" TEXT,
    "email" TEXT,
    "company" TEXT,
    "jobTitle" TEXT,
    "city" TEXT,
    "country" TEXT,
    "notes" TEXT,
    "status" "DataStatus" NOT NULL DEFAULT 'NOT_CONTACTED',
    "batch" TEXT NOT NULL,
    "ownerId" TEXT,
    "convertedLeadId" TEXT,
    "convertedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdById" TEXT,

    CONSTRAINT "DataRecord_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "CaptureLink_tenantId_key_key" ON "CaptureLink"("tenantId", "key");

-- CreateIndex
CREATE INDEX "DataRecord_tenantId_status_createdAt_idx" ON "DataRecord"("tenantId", "status", "createdAt");

-- CreateIndex
CREATE INDEX "DataRecord_tenantId_ownerId_status_idx" ON "DataRecord"("tenantId", "ownerId", "status");

-- CreateIndex
CREATE INDEX "DataRecord_tenantId_batch_idx" ON "DataRecord"("tenantId", "batch");

-- CreateIndex
CREATE INDEX "DataRecord_tenantId_phoneNormalized_idx" ON "DataRecord"("tenantId", "phoneNormalized");

-- AddForeignKey
ALTER TABLE "CaptureLink" ADD CONSTRAINT "CaptureLink_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CaptureLink" ADD CONSTRAINT "CaptureLink_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DataRecord" ADD CONSTRAINT "DataRecord_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DataRecord" ADD CONSTRAINT "DataRecord_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DataRecord" ADD CONSTRAINT "DataRecord_convertedLeadId_fkey" FOREIGN KEY ("convertedLeadId") REFERENCES "Lead"("id") ON DELETE SET NULL ON UPDATE CASCADE;


-- Tenant isolation, same policy as every tenant-scoped table.
DO $$
DECLARE
  target text;
  covered text[] := ARRAY['CaptureLink', 'DataRecord'];
BEGIN
  FOREACH target IN ARRAY covered LOOP
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO master_saas_app', target);
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', target);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', target);
    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I', target);
    EXECUTE format(
      'CREATE POLICY tenant_isolation ON %I FOR ALL '
      'USING ('
      '  "tenantId" = nullif(current_setting(''app.tenant_id'', true), '''')'
      '  OR current_setting(''app.platform_admin'', true) = ''on'''
      ') '
      'WITH CHECK ('
      '  "tenantId" = nullif(current_setting(''app.tenant_id'', true), '''')'
      '  OR current_setting(''app.platform_admin'', true) = ''on'''
      ')',
      target
    );
  END LOOP;
END $$;
