/**
 * Generates docs/ROLES.md from the seeded role specifications and the permission
 * catalogue: for every default role, which modules it can open and, per module,
 * which actions it holds and at what visibility scope. Run with
 *
 *   npx tsx scripts/roles-doc.ts            # rewrite docs/ROLES.md
 *   npx tsx scripts/roles-doc.ts --check    # exit 1 if the file is stale
 *
 * tests/unit/roles-doc.spec.ts runs the check, so a role change that is not
 * reflected in the document fails CI rather than drifting.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { ROLES, type RoleSpec } from '../prisma/seed/roles';
import { PERMISSION_CATALOGUE } from '../src/lib/security/permissionCatalogue';

const SCOPE_WORDS: Record<string, string> = {
  NONE: 'nothing',
  OWN: 'own records',
  TEAM: 'team',
  BRANCH: 'branch',
  REGION: 'region',
  ORGANIZATION: 'whole workspace',
};

/** `'*'` on either level means every catalogue mod or every action in it. */
export function expand(role: RoleSpec): Record<string, Record<string, string>> {
  const out: Record<string, Record<string, string>> = {};
  const modules = Object.keys(role.grants).includes('*') ? Object.keys(PERMISSION_CATALOGUE) : Object.keys(role.grants);
  for (const mod of modules) {
    const spec = role.grants[mod] ?? role.grants['*'] ?? {};
    const actions = Object.keys(spec).includes('*') ? [...(PERMISSION_CATALOGUE[mod] ?? [])] : Object.keys(spec);
    for (const action of actions) {
      const scope = spec[action] ?? spec['*'];
      if (!scope || scope === 'NONE') continue;
      (out[mod] ??= {})[action] = scope;
    }
  }
  return out;
}

const WRITE = new Set(['CREATE', 'EDIT', 'BULK_UPDATE', 'ASSIGN', 'REASSIGN', 'IMPORT', 'UPLOAD']);
const DELETE = new Set(['DELETE']);
const APPROVE = new Set(['APPROVE']);
const REPORT = new Set(['VIEW_REPORTS', 'EXPORT']);

export function render(): string {
  const lines: string[] = [
    '# YOUHAN ONE — default roles and what each can do',
    '',
    '_Generated by `scripts/roles-doc.ts` from `prisma/seed/roles.ts` and the permission catalogue. Do not edit by hand; run the script._',
    '',
    'Rank: lower is more senior; a person can only create, edit or assign roles below their own rank.',
    'Scope: how far the role sees — own records, team, branch, region or the whole workspace. Scope is per permission, not per role.',
    'A workspace administrator can change any of this in **Admin → Roles & permissions**; this document describes the defaults a new workspace starts with.',
    '',
  ];
  for (const role of [...ROLES].sort((a, b) => a.rank - b.rank)) {
    const grants = expand(role);
    const modules = Object.keys(grants).sort();
    lines.push(
      `## ${role.name} (\`${role.key}\`, rank ${role.rank}, default scope ${SCOPE_WORDS[role.defaultScope] ?? role.defaultScope})`,
      '',
    );
    lines.push(`Modules: ${modules.length ? modules.map((m) => `\`${m}\``).join(', ') : '_none_'}`, '');
    lines.push(
      '| Module | Can view | Can change | Can delete | Approves | Reports / export | Other |',
      '|---|---|---|---|---|---|---|',
    );
    for (const mod of modules) {
      const actions = grants[mod];
      const cell = (pick: (a: string) => boolean) =>
        Object.entries(actions)
          .filter(([a]) => pick(a))
          .map(([a, s]) => `${a.toLowerCase().replace(/_/g, ' ')} (${SCOPE_WORDS[s] ?? s})`)
          .join(', ') || '—';
      lines.push(
        `| \`${mod}\` | ${cell((a) => a === 'VIEW' || a === 'VIEW_SENSITIVE_FIELDS')} | ${cell((a) => WRITE.has(a))} | ${cell((a) => DELETE.has(a))} | ${cell((a) => APPROVE.has(a))} | ${cell((a) => REPORT.has(a))} | ${cell((a) => !['VIEW', 'VIEW_SENSITIVE_FIELDS', ...WRITE, ...DELETE, ...APPROVE, ...REPORT].includes(a))} |`,
      );
    }
    lines.push('');
  }
  return lines.join('\n') + '\n';
}

if (process.argv[1] && path.basename(process.argv[1]).startsWith('roles-doc')) {
  const target = path.join(process.cwd(), 'docs', 'ROLES.md');
  const next = render();
  if (process.argv.includes('--check')) {
    const current = readFileSync(target, 'utf8');
    if (current !== next) {
      console.error('docs/ROLES.md is stale — run: npx tsx scripts/roles-doc.ts');
      process.exit(1);
    }
    console.log('docs/ROLES.md is current');
  } else {
    writeFileSync(target, next);
    console.log(`wrote ${target}`);
  }
}
