import type { PermissionAction } from '@prisma/client';

/**
 * Every permission definition the application expects to exist.
 *
 * A `Permission` row is a *definition* — a (module, action) pair a role can be
 * granted. It confers nothing by existing; authority comes only from
 * `RolePermission` rows. A missing definition, though, can never be granted:
 * on a clean install (migrations, first owner, a workspace — no demo seed)
 * twenty-five pairs the code checks had no row, so Service, Documents, Products,
 * Forms, Landing Pages, Automation, Communications, Saved Views and Field Sales
 * could be granted to nobody, and the monitoring allowlist's `tickets:VIEW` was
 * inert.
 *
 * This list is the union of where the catalogue has actually come from: the demo
 * seed's record and admin catalogues, the workspace-provisioning floor, and every
 * pair an earlier migration inserts. Migration
 * `20260915140000_permission_catalogue_definitions` inserts exactly this list,
 * idempotently and **without granting anything**.
 *
 * Adding a module: add it here, write a migration that inserts the new pairs
 * (definitions only), and `tests/unit/permission-catalogue.spec.ts` will insist
 * the two agree and that every navigation and monitoring permission is covered.
 * `scripts/check-permission-catalogue.ts` verifies a migrated database.
 */
export const PERMISSION_CATALOGUE: Readonly<Record<string, readonly PermissionAction[]>> = {
  accounts: [
    'ASSIGN',
    'BULK_UPDATE',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'IMPORT',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'REASSIGN',
    'VIEW',
    'VIEW_SENSITIVE_FIELDS',
  ],
  activities: [
    'ASSIGN',
    'BULK_UPDATE',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'IMPORT',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'REASSIGN',
    'VIEW',
    'VIEW_SENSITIVE_FIELDS',
  ],
  agencyfee: ['APPROVE', 'CREATE', 'VIEW'],
  allocation: ['APPROVE', 'CREATE', 'VIEW'],
  apikeys: [
    'ACCESS_API',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'MANAGE_AUTOMATION',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'VIEW',
    'VIEW_REPORTS',
  ],
  attendance: ['APPROVE', 'CREATE', 'DELETE', 'EDIT', 'MANAGE_CONFIGURATION', 'MANAGE_USERS', 'VIEW'],
  auditlogs: [
    'ACCESS_API',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'MANAGE_AUTOMATION',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'VIEW',
    'VIEW_REPORTS',
  ],
  automation: [
    'ACCESS_API',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'MANAGE_AUTOMATION',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'VIEW',
    'VIEW_REPORTS',
  ],
  bookings: ['CREATE', 'DELETE', 'EDIT', 'VIEW'],
  calls: [
    'ASSIGN',
    'BULK_UPDATE',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'IMPORT',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'REASSIGN',
    'VIEW',
    'VIEW_SENSITIVE_FIELDS',
  ],
  campaigns: [
    'ASSIGN',
    'BULK_UPDATE',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'IMPORT',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'REASSIGN',
    'VIEW',
    'VIEW_SENSITIVE_FIELDS',
  ],
  clientprofiles: ['CREATE', 'DELETE', 'EDIT', 'VIEW'],
  collections: ['APPROVE', 'CREATE', 'VIEW'],
  commissions: ['APPROVE', 'EDIT', 'EXPORT', 'VIEW'],
  commissionslabs: ['APPROVE', 'EDIT', 'VIEW'],
  communications: [
    'ACCESS_API',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'MANAGE_AUTOMATION',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'VIEW',
    'VIEW_REPORTS',
  ],
  contacts: [
    'ASSIGN',
    'BULK_UPDATE',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'IMPORT',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'REASSIGN',
    'VIEW',
    'VIEW_SENSITIVE_FIELDS',
  ],
  contests: ['CREATE', 'EDIT', 'VIEW'],
  dashboards: [
    'ACCESS_API',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'MANAGE_AUTOMATION',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'VIEW',
    'VIEW_REPORTS',
  ],
  departments: ['CREATE', 'DELETE', 'EDIT', 'MANAGE_CONFIGURATION', 'MANAGE_USERS', 'VIEW'],
  dialer: ['CREATE', 'EDIT', 'MANAGE_USERS', 'VIEW'],
  distribution: [
    'ACCESS_API',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'MANAGE_AUTOMATION',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'VIEW',
    'VIEW_REPORTS',
  ],
  documents: [
    'ASSIGN',
    'BULK_UPDATE',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'IMPORT',
    'REASSIGN',
    'VIEW',
    'VIEW_SENSITIVE_FIELDS',
  ],
  employee: ['CREATE', 'DELETE', 'EDIT', 'MANAGE_CONFIGURATION', 'MANAGE_USERS', 'VIEW'],
  events: [
    'ASSIGN',
    'BULK_UPDATE',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'IMPORT',
    'REASSIGN',
    'VIEW',
    'VIEW_SENSITIVE_FIELDS',
  ],
  exports: [
    'ACCESS_API',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'MANAGE_AUTOMATION',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'VIEW',
    'VIEW_REPORTS',
  ],
  fieldsales: [
    'ASSIGN',
    'BULK_UPDATE',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'IMPORT',
    'REASSIGN',
    'VIEW',
    'VIEW_SENSITIVE_FIELDS',
  ],
  forms: [
    'ACCESS_API',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'MANAGE_AUTOMATION',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'VIEW',
    'VIEW_REPORTS',
  ],
  holidays: ['CREATE', 'DELETE', 'EDIT', 'MANAGE_CONFIGURATION', 'MANAGE_USERS', 'VIEW'],
  hr_documents: ['CREATE', 'DELETE', 'EDIT', 'MANAGE_CONFIGURATION', 'MANAGE_USERS', 'VIEW', 'VIEW_SENSITIVE_FIELDS'],
  hr_reports: ['CREATE', 'DELETE', 'EDIT', 'MANAGE_CONFIGURATION', 'MANAGE_USERS', 'VIEW'],
  hrms: ['CREATE', 'DELETE', 'EDIT', 'MANAGE_CONFIGURATION', 'MANAGE_USERS', 'VIEW'],
  imports: [
    'ACCESS_API',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'MANAGE_AUTOMATION',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'VIEW',
    'VIEW_REPORTS',
  ],
  integrations: [
    'ACCESS_API',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'MANAGE_AUTOMATION',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'VIEW',
    'VIEW_REPORTS',
  ],
  landingpages: [
    'ACCESS_API',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'MANAGE_AUTOMATION',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'VIEW',
    'VIEW_REPORTS',
  ],
  leads: [
    'ASSIGN',
    'BULK_UPDATE',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'IMPORT',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'REASSIGN',
    'VIEW',
    'VIEW_SENSITIVE_FIELDS',
  ],
  leave: ['APPROVE', 'CREATE', 'DELETE', 'EDIT', 'MANAGE_CONFIGURATION', 'MANAGE_USERS', 'VIEW'],
  listings: ['CREATE', 'DELETE', 'EDIT', 'EXPORT', 'VIEW', 'VIEW_SENSITIVE_FIELDS'],
  lists: [
    'ACCESS_API',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'MANAGE_AUTOMATION',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'VIEW',
    'VIEW_REPORTS',
  ],
  opportunities: [
    'ASSIGN',
    'BULK_UPDATE',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'IMPORT',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'REASSIGN',
    'VIEW',
    'VIEW_SENSITIVE_FIELDS',
  ],
  overtime: ['APPROVE', 'CREATE', 'DELETE', 'EDIT', 'MANAGE_CONFIGURATION', 'MANAGE_USERS', 'VIEW'],
  payouts: ['APPROVE', 'CREATE', 'VIEW'],
  payroll: ['APPROVE', 'CREATE', 'EDIT', 'EXPORT', 'VIEW'],
  performance: ['APPROVE', 'CREATE', 'EDIT', 'VIEW'],
  posts: ['CREATE', 'DELETE', 'EDIT', 'VIEW'],
  products: [
    'ASSIGN',
    'BULK_UPDATE',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'IMPORT',
    'REASSIGN',
    'VIEW',
    'VIEW_SENSITIVE_FIELDS',
  ],
  projects: ['CREATE', 'DELETE', 'EDIT', 'EXPORT', 'VIEW'],
  recruitment: ['APPROVE', 'CREATE', 'DELETE', 'EDIT', 'VIEW', 'VIEW_SENSITIVE_FIELDS'],
  referrals: ['CREATE', 'EDIT', 'VIEW'],
  reports: [
    'ACCESS_API',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'MANAGE_AUTOMATION',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'VIEW',
    'VIEW_REPORTS',
  ],
  requirements: ['CREATE', 'DELETE', 'EDIT', 'VIEW'],
  roles: [
    'ACCESS_API',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'MANAGE_AUTOMATION',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'VIEW',
    'VIEW_REPORTS',
  ],
  settings: [
    'ACCESS_API',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'MANAGE_AUTOMATION',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'VIEW',
    'VIEW_REPORTS',
  ],
  shifts: ['APPROVE', 'CREATE', 'DELETE', 'EDIT', 'MANAGE_CONFIGURATION', 'MANAGE_USERS', 'VIEW'],
  sla: [
    'ACCESS_API',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'MANAGE_AUTOMATION',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'VIEW',
    'VIEW_REPORTS',
  ],
  smartviews: [
    'ACCESS_API',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'MANAGE_AUTOMATION',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'VIEW',
    'VIEW_REPORTS',
  ],
  tasks: [
    'ASSIGN',
    'BULK_UPDATE',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'IMPORT',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'REASSIGN',
    'VIEW',
    'VIEW_SENSITIVE_FIELDS',
  ],
  testimonials: ['APPROVE', 'CREATE', 'EDIT', 'VIEW'],
  tickets: [
    'ASSIGN',
    'BULK_UPDATE',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'IMPORT',
    'REASSIGN',
    'VIEW',
    'VIEW_SENSITIVE_FIELDS',
  ],
  users: [
    'ACCESS_API',
    'CREATE',
    'DELETE',
    'EDIT',
    'EXPORT',
    'MANAGE_AUTOMATION',
    'MANAGE_CONFIGURATION',
    'MANAGE_USERS',
    'VIEW',
    'VIEW_REPORTS',
  ],
  visits: ['APPROVE', 'CREATE', 'DELETE', 'EDIT', 'MANAGE_USERS', 'VIEW'],
  work_locations: ['CREATE', 'DELETE', 'EDIT', 'MANAGE_CONFIGURATION', 'MANAGE_USERS', 'VIEW'],
};

/** The catalogue as `module:ACTION` tokens. */
export const catalogueTokens = (): string[] =>
  Object.entries(PERMISSION_CATALOGUE).flatMap(([module, actions]) => actions.map((action) => `${module}:${action}`));
