/**
 * The seeded role catalogue: who exists in a new workspace and what each may do.
 *
 * Its own file because two things need it and they must not drift. The seed
 * builds a workspace from it, and scripts/seed-role-defaults.ts repairs an
 * existing one — a second copy of this matrix would be wrong within a month.
 *
 * Every cell here is only a default. Administrators edit them afterwards from
 * Roles & permissions, and a revoked permission deletes its row rather than
 * setting a flag, which is why the repair script only fills roles that hold no
 * grants at all: a partially granted role cannot be told apart from one an
 * administrator has deliberately trimmed.
 *
 * Mirrors the matrix in docs/01-PERMISSIONS.md section 4.
 */
import type { VisibilityScope as Scope } from '@prisma/client';

export interface RoleSpec {
  key: string;
  name: string;
  rank: number;
  defaultScope: Scope;
  grants: Record<string, Partial<Record<string, Scope>>>;
}

export const A: Scope = 'ORGANIZATION',
  R: Scope = 'REGION',
  B: Scope = 'BRANCH',
  T: Scope = 'TEAM',
  O: Scope = 'OWN';

export const ROLES: RoleSpec[] = [
  { key: 'super_admin', name: 'Super Administrator', rank: 0, defaultScope: A, grants: { '*': { '*': A } } },
  { key: 'org_admin', name: 'Organization Administrator', rank: 10, defaultScope: A, grants: { '*': { '*': A } } },
  {
    key: 'sales_director',
    name: 'Sales Director',
    rank: 20,
    defaultScope: A,
    grants: {
      leads: {
        VIEW: A,
        CREATE: A,
        EDIT: A,
        ASSIGN: A,
        REASSIGN: A,
        BULK_UPDATE: A,
        EXPORT: A,
        IMPORT: A,
        VIEW_SENSITIVE_FIELDS: A,
      },
      opportunities: { VIEW: A, CREATE: A, EDIT: A, DELETE: A, EXPORT: A },
      accounts: { VIEW: A, EDIT: A },
      contacts: { VIEW: A },
      activities: { VIEW: A, CREATE: A },
      tasks: { VIEW: A, ASSIGN: A },
      products: { VIEW: A, EDIT: A },
      documents: { VIEW: A },
      campaigns: { VIEW: A },
      reports: { VIEW: A, CREATE: A, VIEW_REPORTS: A },
      dashboards: { VIEW: A, CREATE: A },
      smartviews: { VIEW: A, CREATE: A },
      distribution: { VIEW: A, MANAGE_CONFIGURATION: A },
      fieldsales: { VIEW: A },
    },
  },
  {
    key: 'regional_manager',
    name: 'Regional Manager',
    rank: 30,
    defaultScope: R,
    grants: {
      leads: {
        VIEW: R,
        CREATE: R,
        EDIT: R,
        ASSIGN: R,
        REASSIGN: R,
        BULK_UPDATE: R,
        EXPORT: R,
        IMPORT: R,
        VIEW_SENSITIVE_FIELDS: R,
      },
      opportunities: { VIEW: R, CREATE: R, EDIT: R },
      accounts: { VIEW: R, EDIT: R },
      contacts: { VIEW: R },
      activities: { VIEW: R, CREATE: R },
      tasks: { VIEW: R, ASSIGN: R },
      documents: { VIEW: R },
      products: { VIEW: A },
      reports: { VIEW: R, CREATE: R, VIEW_REPORTS: R },
      dashboards: { VIEW: R, CREATE: R },
      smartviews: { VIEW: R, CREATE: R },
      fieldsales: { VIEW: R },
    },
  },
  {
    key: 'branch_manager',
    name: 'Branch Manager',
    rank: 40,
    defaultScope: B,
    grants: {
      leads: {
        VIEW: B,
        CREATE: B,
        EDIT: B,
        ASSIGN: B,
        REASSIGN: B,
        BULK_UPDATE: B,
        EXPORT: B,
        IMPORT: B,
        VIEW_SENSITIVE_FIELDS: B,
      },
      opportunities: { VIEW: B, CREATE: B, EDIT: B },
      accounts: { VIEW: B, EDIT: B },
      contacts: { VIEW: B },
      activities: { VIEW: B, CREATE: B },
      tasks: { VIEW: B, ASSIGN: B },
      documents: { VIEW: B },
      products: { VIEW: A },
      tickets: { VIEW: B },
      reports: { VIEW: B, CREATE: B, VIEW_REPORTS: B },
      dashboards: { VIEW: B, CREATE: B },
      smartviews: { VIEW: B, CREATE: B },
      fieldsales: { VIEW: B },
    },
  },
  {
    key: 'team_manager',
    name: 'Team Manager',
    rank: 50,
    defaultScope: T,
    grants: {
      leads: { VIEW: T, CREATE: T, EDIT: T, ASSIGN: T, REASSIGN: T, BULK_UPDATE: T },
      opportunities: { VIEW: T, CREATE: T, EDIT: T },
      accounts: { VIEW: T, EDIT: T },
      contacts: { VIEW: T },
      activities: { VIEW: T, CREATE: T },
      tasks: { VIEW: T, ASSIGN: T },
      documents: { VIEW: T },
      products: { VIEW: A },
      reports: { VIEW: T, VIEW_REPORTS: T },
      smartviews: { VIEW: T, CREATE: T },
      dashboards: { VIEW: T },
      fieldsales: { VIEW: T },
    },
  },
  {
    key: 'sales_rep',
    name: 'Sales Representative',
    rank: 60,
    defaultScope: O,
    grants: {
      leads: { VIEW: O, CREATE: O, EDIT: O },
      opportunities: { VIEW: O, CREATE: O, EDIT: O },
      accounts: { VIEW: T },
      contacts: { VIEW: T },
      activities: { VIEW: O, CREATE: O },
      tasks: { VIEW: O, CREATE: O, EDIT: O },
      documents: { VIEW: O },
      products: { VIEW: A },
      reports: { VIEW: O, VIEW_REPORTS: O },
      smartviews: { VIEW: O, CREATE: O },
      dashboards: { VIEW: O },
    },
  },
  {
    key: 'field_rep',
    name: 'Field Sales Representative',
    rank: 60,
    defaultScope: O,
    grants: {
      leads: { VIEW: O, CREATE: O, EDIT: O },
      opportunities: { VIEW: O, EDIT: O },
      accounts: { VIEW: T },
      contacts: { VIEW: T },
      activities: { VIEW: O, CREATE: O },
      tasks: { VIEW: O, CREATE: O, EDIT: O },
      documents: { VIEW: O },
      products: { VIEW: A },
      fieldsales: { VIEW: O, CREATE: O, EDIT: O },
      smartviews: { VIEW: O },
    },
  },
  {
    key: 'marketing_manager',
    name: 'Marketing Manager',
    rank: 40,
    defaultScope: A,
    grants: {
      leads: { VIEW: A, CREATE: A, EDIT: T, BULK_UPDATE: T, EXPORT: A, IMPORT: A },
      opportunities: { VIEW: A },
      accounts: { VIEW: A },
      contacts: { VIEW: A },
      activities: { VIEW: A, CREATE: A },
      campaigns: { VIEW: A, CREATE: A, EDIT: A, DELETE: A },
      lists: { VIEW: A, CREATE: A, EDIT: A },
      forms: { VIEW: A, CREATE: A, MANAGE_CONFIGURATION: A },
      landingpages: { VIEW: A, CREATE: A, MANAGE_CONFIGURATION: A },
      communications: { VIEW: A, CREATE: A },
      automation: { VIEW: A, MANAGE_AUTOMATION: A },
      reports: { VIEW: A, CREATE: A, VIEW_REPORTS: A },
      dashboards: { VIEW: A, CREATE: A },
      products: { VIEW: A },
      smartviews: { VIEW: A, CREATE: A },
    },
  },
  {
    key: 'marketing_exec',
    name: 'Marketing Executive',
    rank: 60,
    defaultScope: O,
    grants: {
      leads: { VIEW: T, CREATE: T, EDIT: O },
      contacts: { VIEW: T },
      campaigns: { VIEW: O, CREATE: O, EDIT: O },
      lists: { VIEW: O, CREATE: O },
      communications: { VIEW: O, CREATE: O },
      activities: { VIEW: O, CREATE: O },
      tasks: { VIEW: O },
      reports: { VIEW: O, VIEW_REPORTS: O },
      products: { VIEW: A },
      smartviews: { VIEW: O },
    },
  },
  {
    key: 'service_manager',
    name: 'Customer Service Manager',
    rank: 40,
    defaultScope: A,
    grants: {
      tickets: { VIEW: A, CREATE: A, EDIT: A, ASSIGN: A, DELETE: A, EXPORT: A },
      sla: { VIEW: A, MANAGE_CONFIGURATION: A },
      accounts: { VIEW: A },
      contacts: { VIEW: A },
      leads: { VIEW: B },
      activities: { VIEW: B, CREATE: B },
      tasks: { VIEW: B, ASSIGN: B },
      documents: { VIEW: B },
      communications: { VIEW: A, CREATE: A },
      forms: { VIEW: A, MANAGE_CONFIGURATION: A },
      automation: { VIEW: A, MANAGE_AUTOMATION: A },
      reports: { VIEW: A, CREATE: A, VIEW_REPORTS: A },
      dashboards: { VIEW: A, CREATE: A },
      products: { VIEW: A },
      smartviews: { VIEW: A },
    },
  },
  {
    key: 'service_agent',
    name: 'Customer Service Agent',
    rank: 60,
    defaultScope: T,
    grants: {
      tickets: { VIEW: T, CREATE: T, EDIT: T },
      accounts: { VIEW: T },
      contacts: { VIEW: T },
      leads: { VIEW: T },
      activities: { VIEW: T, CREATE: T },
      tasks: { VIEW: T },
      documents: { VIEW: T },
      communications: { VIEW: T, CREATE: T },
      products: { VIEW: A },
      reports: { VIEW: T, VIEW_REPORTS: T },
      smartviews: { VIEW: T },
    },
  },
  {
    key: 'analyst',
    name: 'Reporting Analyst',
    rank: 45,
    defaultScope: A,
    grants: {
      leads: { VIEW: A, EXPORT: A },
      opportunities: { VIEW: A, EXPORT: A },
      accounts: { VIEW: A },
      contacts: { VIEW: A },
      activities: { VIEW: A },
      tasks: { VIEW: A },
      tickets: { VIEW: A },
      campaigns: { VIEW: A },
      documents: { VIEW: A },
      fieldsales: { VIEW: A },
      products: { VIEW: A },
      auditlogs: { VIEW: A },
      reports: { VIEW: A, CREATE: A, EDIT: A, EXPORT: A, VIEW_REPORTS: A },
      dashboards: { VIEW: A, CREATE: A },
      smartviews: { VIEW: A, CREATE: A },
      // Call review: the analyst is also the call-quality reviewer — reads
      // calls, transcripts and audits organisation-wide, changes nothing.
      calls: { VIEW: A },
      events: { VIEW: A },
    },
  },
  // -- HR and the back office ------------------------------------------------
  //
  // These roles existed in the database with no grants at all, which is why HR
  // staff could open the module and do nothing in it, and why an employee could
  // not read their own record. They were never in this list, so a fresh seed
  // never created them either.
  //
  // Two rules shape the split. Approving is separated from preparing: the
  // payroll officer who builds a run cannot release it, and the recruiter who
  // moves a candidate cannot decide the offer. And each scope is the smallest
  // that lets the role work, so a department manager approves for their own
  // team rather than the company.
  {
    key: 'hr_admin',
    name: 'HR Administrator',
    rank: 20,
    defaultScope: A,
    grants: {
      employee: { VIEW: A, CREATE: A, EDIT: A, DELETE: A, EXPORT: A, VIEW_SENSITIVE_FIELDS: A },
      employees: { VIEW: A, CREATE: A, EDIT: A, EXPORT: A },
      attendance: { VIEW: A, CREATE: A, EDIT: A, APPROVE: A, EXPORT: A, VIEW_REPORTS: A },
      leave: { VIEW: A, CREATE: A, EDIT: A, APPROVE: A, EXPORT: A },
      overtime: { VIEW: A, CREATE: A, EDIT: A, APPROVE: A },
      shifts: { VIEW: A, CREATE: A, EDIT: A, DELETE: A, APPROVE: A },
      holidays: { VIEW: A, CREATE: A, EDIT: A, DELETE: A },
      hr_documents: { VIEW: A, CREATE: A, EDIT: A, DELETE: A, EXPORT: A },
      hr_reports: { VIEW: A, VIEW_REPORTS: A, EXPORT: A },
      hrms: { VIEW: A, EDIT: A, MANAGE_CONFIGURATION: A },
      recruitment: { VIEW: A, CREATE: A, EDIT: A, APPROVE: A },
      performance: { VIEW: A, CREATE: A, EDIT: A, APPROVE: A },
      work_locations: { VIEW: A, CREATE: A, EDIT: A, DELETE: A, MANAGE_CONFIGURATION: A },
      departments: { VIEW: A, CREATE: A, EDIT: A },
      // Enough to onboard a joiner and reset their password, but not to edit
      // the role catalogue: deciding what a role may do stays with the org
      // admin, or an HR lead could widen their own authority.
      users: { VIEW: A, CREATE: A, EDIT: A, MANAGE_USERS: A },
      roles: { VIEW: A, ASSIGN: A },
      auditlogs: { VIEW: A },
      payroll: { VIEW: A },
      documents: { VIEW: A, CREATE: A },
      reports: { VIEW: A, VIEW_REPORTS: A },
      dashboards: { VIEW: A },
    },
  },
  {
    key: 'hr_executive',
    name: 'HR Executive',
    rank: 50,
    defaultScope: A,
    // Day-to-day HR: records and requests, but no approvals and no salaries.
    grants: {
      employee: { VIEW: A, CREATE: A, EDIT: A },
      employees: { VIEW: A, EDIT: A },
      attendance: { VIEW: A, CREATE: A, EDIT: A },
      leave: { VIEW: A, CREATE: A, EDIT: A },
      overtime: { VIEW: A, CREATE: A },
      shifts: { VIEW: A, CREATE: A, EDIT: A },
      holidays: { VIEW: A },
      hr_documents: { VIEW: A, CREATE: A, EDIT: A },
      hr_reports: { VIEW: A },
      hrms: { VIEW: A },
      recruitment: { VIEW: A, CREATE: A, EDIT: A },
      performance: { VIEW: A, CREATE: A },
      work_locations: { VIEW: A },
      departments: { VIEW: A },
      users: { VIEW: A },
      dashboards: { VIEW: A },
    },
  },
  {
    key: 'payroll_officer',
    name: 'Payroll Officer',
    rank: 55,
    defaultScope: A,
    // Prepares runs, never releases them. No APPROVE anywhere, on purpose.
    grants: {
      payroll: { VIEW: A, CREATE: A, EDIT: A, EXPORT: A, VIEW_SENSITIVE_FIELDS: A },
      overtime: { VIEW: A },
      attendance: { VIEW: A, VIEW_REPORTS: A, EXPORT: A },
      leave: { VIEW: A },
      employee: { VIEW: A, VIEW_SENSITIVE_FIELDS: A },
      employees: { VIEW: A },
      hr_reports: { VIEW: A, VIEW_REPORTS: A, EXPORT: A },
      hrms: { VIEW: A },
      dashboards: { VIEW: A },
    },
  },
  {
    key: 'recruiter',
    name: 'Recruiter',
    rank: 60,
    defaultScope: A,
    // Moves candidates through the pipeline; the offer decision is HR policy.
    grants: {
      recruitment: { VIEW: A, CREATE: A, EDIT: A, EXPORT: A },
      employee: { VIEW: A },
      employees: { VIEW: A },
      hr_documents: { VIEW: A, CREATE: A },
      departments: { VIEW: A },
      hrms: { VIEW: A },
      dashboards: { VIEW: A },
    },
  },
  {
    key: 'dept_manager',
    name: 'Department Manager',
    rank: 45,
    defaultScope: T,
    // Approves for their own people only. The scope is the whole point.
    grants: {
      employee: { VIEW: T },
      employees: { VIEW: T },
      attendance: { VIEW: T, APPROVE: T, VIEW_REPORTS: T },
      leave: { VIEW: T, APPROVE: T },
      overtime: { VIEW: T, APPROVE: T },
      shifts: { VIEW: T, EDIT: T },
      performance: { VIEW: T, CREATE: T, EDIT: T },
      hr_reports: { VIEW: T },
      hrms: { VIEW: T },
      tasks: { VIEW: T, ASSIGN: T },
      dashboards: { VIEW: T },
    },
  },
  {
    key: 'site_manager',
    name: 'Site Manager',
    rank: 48,
    defaultScope: B,
    // The same authority as a department manager, drawn around a place rather
    // than a team, which is how a site with mixed reporting lines works.
    grants: {
      employee: { VIEW: B },
      employees: { VIEW: B },
      attendance: { VIEW: B, APPROVE: B, VIEW_REPORTS: B },
      leave: { VIEW: B, APPROVE: B },
      overtime: { VIEW: B, APPROVE: B },
      shifts: { VIEW: B, CREATE: B, EDIT: B },
      work_locations: { VIEW: B },
      hr_reports: { VIEW: B },
      hrms: { VIEW: B },
      dashboards: { VIEW: B },
    },
  },
  {
    key: 'it_admin',
    name: 'IT Administrator',
    rank: 30,
    defaultScope: A,
    // Runs the plumbing and deliberately holds no HR or Sales record access:
    // administering accounts is not a reason to be able to read salaries.
    grants: {
      users: { VIEW: A, CREATE: A, EDIT: A, MANAGE_USERS: A },
      roles: { VIEW: A, ASSIGN: A },
      settings: { VIEW: A, EDIT: A, MANAGE_CONFIGURATION: A },
      integrations: { VIEW: A, CREATE: A, EDIT: A, DELETE: A, MANAGE_CONFIGURATION: A },
      apikeys: { VIEW: A, CREATE: A, DELETE: A, ACCESS_API: A },
      auditlogs: { VIEW: A, EXPORT: A },
      imports: { VIEW: A, IMPORT: A },
      exports: { VIEW: A, EXPORT: A },
      automation: { VIEW: A, MANAGE_AUTOMATION: A },
      dashboards: { VIEW: A },
    },
  },
  {
    key: 'finance_admin',
    name: 'Finance Administrator',
    rank: 35,
    defaultScope: A,
    // The approving half of the payroll split above.
    grants: {
      payroll: { VIEW: A, APPROVE: A, EXPORT: A, VIEW_SENSITIVE_FIELDS: A },
      commissions: { VIEW: A, CREATE: A, EDIT: A, APPROVE: A, EXPORT: A },
      commissionslabs: { VIEW: A, EDIT: A },
      payouts: { VIEW: A, APPROVE: A, EXPORT: A },
      overtime: { VIEW: A, APPROVE: A },
      reports: { VIEW: A, VIEW_REPORTS: A, EXPORT: A },
      hr_reports: { VIEW: A, VIEW_REPORTS: A, EXPORT: A },
      exports: { VIEW: A, EXPORT: A },
      auditlogs: { VIEW: A },
      dashboards: { VIEW: A },
    },
  },
  {
    key: 'auditor',
    name: 'Auditor',
    rank: 70,
    defaultScope: A,
    // Reads what matters and writes nothing: no CREATE, EDIT, DELETE or
    // APPROVE anywhere. An auditor who can change the record is not one.
    grants: {
      auditlogs: { VIEW: A, EXPORT: A },
      employee: { VIEW: A },
      employees: { VIEW: A },
      attendance: { VIEW: A, VIEW_REPORTS: A, EXPORT: A },
      leave: { VIEW: A },
      overtime: { VIEW: A },
      payroll: { VIEW: A },
      hr_documents: { VIEW: A },
      hr_reports: { VIEW: A, VIEW_REPORTS: A, EXPORT: A },
      hrms: { VIEW: A },
      work_locations: { VIEW: A },
      roles: { VIEW: A },
      users: { VIEW: A },
      settings: { VIEW: A },
      reports: { VIEW: A, VIEW_REPORTS: A },
      dashboards: { VIEW: A },
    },
  },
  {
    key: 'employee',
    name: 'Employee',
    rank: 90,
    defaultScope: O,
    // Their own record, and nothing wider. Biometric consent and check-in are
    // absent on purpose: those live on the self-service route, authorised by
    // being the account in question rather than by holding a module grant.
    grants: {
      employee: { VIEW: O, EDIT: O },
      attendance: { VIEW: O },
      leave: { VIEW: O, CREATE: O },
      overtime: { VIEW: O, CREATE: O },
      hr_documents: { VIEW: O },
      payroll: { VIEW: O },
      shifts: { VIEW: O },
      // The public holiday calendar is the same for everyone.
      holidays: { VIEW: A },
      performance: { VIEW: O, EDIT: O },
      hrms: { VIEW: O },
      tasks: { VIEW: O, EDIT: O },
      dashboards: { VIEW: O },
    },
  },
  {
    key: 'read_only',
    name: 'Read-Only User',
    rank: 90,
    defaultScope: T,
    grants: {
      leads: { VIEW: T },
      opportunities: { VIEW: T },
      accounts: { VIEW: T },
      contacts: { VIEW: T },
      activities: { VIEW: T },
      tasks: { VIEW: T },
      tickets: { VIEW: T },
      products: { VIEW: A },
      reports: { VIEW: T, VIEW_REPORTS: T },
      dashboards: { VIEW: T },
      smartviews: { VIEW: T },
    },
  },
];
